title: <center>Mari Kambe</center> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center>
  My portfolio page
  <br><br>
  <a href="https://www.linkedin.com/in/mari-kambe-b5a638a8/"><img src="https://img.icons8.com/ios-filled/48/000000/linkedin.png"></a>
  <a href="https://github.com/marientje"><img src="https://img.icons8.com/windows/48/000000/github-2.png"></a>
  </center>
theme: jekyll-theme-minimal
